name: GitHub Actions Services

on:
  push:
    branches:
      - main

jobs:
  ekyc_services:
    runs-on: ubuntu-latest

    services:
      ekyc_redis:
        image: redis
        ports:
          - 6379:6379

      ekyc_postgres:
        image: postgres:11
        env:
          POSTGRES_USER: kong
          POSTGRES_PASSWORD: kong
          POSTGRES_DB: kong
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data

      kong_db:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_PASSWORD: kongpass
          POSTGRES_DB: kong
        ports:
          - 5000:5432
        volumes:
          - kongdata:/var/lib/postgresql/data

      kong_migration:
        image: kong/kong-gateway:3.1.1.3
        env:
          KONG_DATABASE: postgres
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kongpass
          KONG_PG_DATABASE: kong
          KONG_PG_HOST: kong_postgres

      kong:
        image: kong/kong-gateway:3.1.1.3
        ports:
          - 8080:8080
          - 8001:8001
          - 8002:8002
          - 8003:8003
          - 8443:8443
          - 8444:8444
          - 8445:8445
        env:
          KONG_LOG_LEVEL: info
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kongpass
          KONG_PG_DATABASE: kong
          KONG_PG_HOST: kong_postgres
          KONG_PROXY_ACCESS_LOG: /dev/stdout
          KONG_ADMIN_ACCESS_LOG: /dev/stdout
          KONG_PROXY_ERROR_LOG: /dev/stderr
          KONG_ADMIN_ERROR_LOG: /dev/stderr
          KONG_ADMIN_LISTEN: 0.0.0.0:8001
          KONG_ADMIN_GUI_URL: http://127.0.0.1:8002
          KONG_DATABASE: postgres

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Setup PostgreSQL
        run: docker exec ekyc_postgres1 pg_isready -U kong -d kong

      - name: Setup Kong Database
        run: docker exec kong_postgres pg_isready -U kong -d kong

      - name: Wait for Kong Migration
        run: docker exec kong_migration kong migrations up

