name: GitHub Actions Services
on:
  push:
    branches:
      - main
env:
  APP_NAME: ekyc-api
  APP_NAMESPACE: ekyc
  ONEAPI_APP_ID: 9708287b-6fe2-4c00-b5a5-c20d35d62e73
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      SECRET_KEY: "abc1234"
      DEBUG_MODE: "True"
      ROOT_LOG_LEVEL: "DEBUG"
      LOCAL: "True"
      DB_USER: ekycdbuser
      DB_PASSWORD: postgres1234
      DB_NAME: ekyc_test
      X_CLAIMS: ${{ secrets.X_CLAIMS }}
      KONG_ONEAPI_SIGNING_KEY: ${{ secrets.KONG_ONEAPI_SIGNING_KEY }}
      KONG_ADMIN_URL: http://127.0.0.1:8001
    services:
      postgres_main:
        image: postgres:11
        env:
          POSTGRES_USER: kong
          POSTGRES_PASSWORD: kong
          POSTGRES_DB: kong
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      redis_main:
        image: redis:7
        ports:
          - 6379:6379
      kong_db:
        image: 'postgres:13'
        env: 
          POSTGRES_USER: kong
          POSTGRES_PASSWORD: kongpass
          POSTGRES_DB: kong
        ports:
          - '5000:5432'
      kong_migration:
        image: 'kong/kong-gateway:3.1.1.3'
        env:
          KONG_DATABASE: postgres
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kongpass
          KONG_PG_DATABASE: kong
          KONG_PG_HOST: kong_postgres
        ports:
          - '8000:8000'
        # healthcheck:
        #   test: ["CMD", "kong", "health"]
        #   interval: 60s
        #   timeout: 10s
        #   retries: 10
    steps:
      - name: Run Kong Migrations
        run: docker exec kong_migration kong migrations bootstrap
        env:
          KONG_DATABASE: postgres
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kongpass
          KONG_PG_DATABASE: kong
          KONG_PG_HOST: kong_postgres
      kong_main:
        image: 'kong/kong-gateway:3.1.1.3'
        env:
          KONG_LOG_LEVEL: info
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kongpass
          KONG_PG_DATABASE: kong
          KONG_PG_HOST: kong_postgres
          KONG_PROXY_ACCESS_LOG: /dev/stdout
          KONG_ADMIN_ACCESS_LOG: /dev/stdout
          KONG_PROXY_ERROR_LOG: /dev/stderr
          KONG_ADMIN_ERROR_LOG: /dev/stderr
          KONG_ADMIN_LISTEN: 0.0.0.0:8001
          KONG_ADMIN_GUI_URL: http://127.0.0.1:8002
          KONG_ONEAPI_APIM_ENVIRONMENT: development
          KONG_DATABASE: postgres
        ports:
          - 8080:8080
          - 8001:8001
          - 8002:8002
          - 8003:8003
          - 8443:8443
          - 8444:8444
          - 8445:8445
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    
    steps:        
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
